# Generated by Django 4.1.5 on 2023-01-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSeparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separator', models.CharField(choices=[('Comma(,)', ','), ('Semicolon (;)', ';'), ('Tab(\t)', '\t'), ('Space( )', ' '), ('Pipe(|)', '|')], default='Comma(,)', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'ColumnSeparators',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_type', models.CharField(max_length=100)),
                ('var_list', models.TextField(blank=True)),
                ('range_min', models.IntegerField(blank=True)),
                ('range_max', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'DataTypes',
            },
        ),
        migrations.CreateModel(
            name='StringCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_char', models.CharField(choices=[('Double-quote(")', '"'), ('Quote', "'")], default='Double-quote(")', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'StringCharacters',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_created', models.BooleanField(default=False)),
                ('rows_num', models.PositiveBigIntegerField(default=100)),
                ('column_separator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.columnseparator')),
                ('data_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datatype')),
                ('string_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stringcharacter')),
            ],
            options={
                'verbose_name_plural': 'Schemas',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('col_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datatype')),
            ],
            options={
                'verbose_name_plural': 'Columns',
            },
        ),
    ]
