# Generated by Django 4.1.5 on 2023-03-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('range_min', models.PositiveIntegerField(blank=True, null=True)),
                ('range_max', models.PositiveIntegerField(blank=True, null=True)),
                ('col_type', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('row_num', models.IntegerField(default=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='schema',
            name='data_types',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='rows_num',
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='ColumnSeparator',
        ),
        migrations.DeleteModel(
            name='DataType',
        ),
        migrations.DeleteModel(
            name='StringCharacter',
        ),
        migrations.AddField(
            model_name='columnitem',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='main.schema'),
        ),
    ]
