# Generated by Django 4.1.5 on 2023-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_datafile_delete_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='file',
            field=models.FileField(default=1, upload_to='not_used'),
            preserve_default=False,
        ),
    ]
