# Generated by Django 4.1.5 on 2023-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_datafile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFile',
        ),
        migrations.AddField(
            model_name='schema',
            name='file_link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
