# Generated by Django 4.1.5 on 2023-03-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_datafile_schema_file_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnitem',
            options={'ordering': ('order',)},
        ),
    ]
